libc_a_SOURCES += \
	%D%/setjmp.S %D%/strcmp.S %D%/strcpy.c \
	%D%/aeabi_memcpy.c %D%/aeabi_memcpy-armv7a.S \
	%D%/aeabi_memmove.c %D%/aeabi_memmove-soft.S \
	%D%/aeabi_memset.c %D%/aeabi_memset-soft.S %D%/aeabi_memclr.c \
	%D%/memchr-stub.c \
	%D%/memchr.S \
	%D%/memcmp-stub.c \
	%D%/memcmp.S \
	%D%/memcpy-stub.c \
	%D%/memcpy.S \
	%D%/memcpy-vita-large.S \
	%D%/memmove-stub.c \
	%D%/memmove.S \
	%D%/memset-stub.c \
	%D%/memset.S \
	%D%/strlen-stub.c \
	%D%/strlen.S
